version: "3.2"

services:
  spicedb:
    image: authzed/spicedb:v1.20.0
    command: "serve"
    restart: "on-failure"
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50051:50051"
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=somerandomkeyhere"
      - "SPICEDB_DATASTORE_ENGINE=memory"
